import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ModelListService {
  public readonly modelList: object[]
  public readonly brandList: object[]
  constructor() {
    this.modelList = [
      {"modelId":1,"modelName":"ILX","brandId":1},
      {"modelId":2,"modelName":"MDX","brandId":1},
      {"modelId":3,"modelName":"MDX Sport Hybrid","brandId":1},
      {"modelId":4,"modelName":"NSX","brandId":1},
      {"modelId":5,"modelName":"RDX","brandId":1},
      {"modelId":6,"modelName":"RLX","brandId":1},
      {"modelId":7,"modelName":"RLX Sport Hybrid","brandId":1},
      {"modelId":8,"modelName":"TLX","brandId":1},
      {"modelId":9,"modelName":"4C Spider","brandId":2},
      {"modelId":10,"modelName":"Giulia","brandId":2},
      {"modelId":11,"modelName":"Stelvio","brandId":2},
      {"modelId":12,"modelName":"A3","brandId":3},
      {"modelId":13,"modelName":"A4","brandId":3},
      {"modelId":14,"modelName":"A5","brandId":3},
      {"modelId":15,"modelName":"A6","brandId":3},
      {"modelId":16,"modelName":"A6 allroad","brandId":3},
      {"modelId":17,"modelName":"A7","brandId":3},
      {"modelId":18,"modelName":"Q3","brandId":3},
      {"modelId":19,"modelName":"Q5","brandId":3},
      {"modelId":20,"modelName":"Q7","brandId":3},
      {"modelId":21,"modelName":"Q8","brandId":3},
      {"modelId":22,"modelName":"R8","brandId":3},
      {"modelId":23,"modelName":"S4","brandId":3},
      {"modelId":24,"modelName":"S8","brandId":3},
      {"modelId":25,"modelName":"SQ5","brandId":3},
      {"modelId":26,"modelName":"TT","brandId":3},
      {"modelId":27,"modelName":"2 Series","brandId":4},
      {"modelId":28,"modelName":"3 Series","brandId":4},
      {"modelId":29,"modelName":"4 Series","brandId":4},
      {"modelId":30,"modelName":"5 Series","brandId":4},
      {"modelId":31,"modelName":"7 Series","brandId":4},
      {"modelId":32,"modelName":"8 Series","brandId":4},
      {"modelId":33,"modelName":"M2","brandId":4},
      {"modelId":34,"modelName":"X1","brandId":4},
      {"modelId":35,"modelName":"X2","brandId":4},
      {"modelId":36,"modelName":"X3","brandId":4},
      {"modelId":37,"modelName":"X3 M","brandId":4},
      {"modelId":38,"modelName":"X4","brandId":4},
      {"modelId":39,"modelName":"X5","brandId":4},
      {"modelId":40,"modelName":"X6","brandId":4},
      {"modelId":41,"modelName":"X7","brandId":4},
      {"modelId":42,"modelName":"Z4","brandId":4},
      {"modelId":43,"modelName":"Enclave","brandId":5},
      {"modelId":44,"modelName":"Encore","brandId":5},
      {"modelId":45,"modelName":"Encore GX","brandId":5},
      {"modelId":46,"modelName":"Envision","brandId":5},
      {"modelId":47,"modelName":"Regal Sportback","brandId":5},
      {"modelId":48,"modelName":"Regal TourX","brandId":5},
      {"modelId":49,"modelName":"CT4","brandId":6},
      {"modelId":50,"modelName":"CT5","brandId":6},
      {"modelId":51,"modelName":"CT6","brandId":6},
      {"modelId":52,"modelName":"CT6-V","brandId":6},
      {"modelId":53,"modelName":"Escalade","brandId":6},
      {"modelId":54,"modelName":"Escalade ESV","brandId":6},
      {"modelId":55,"modelName":"XT4","brandId":6},
      {"modelId":56,"modelName":"XT5","brandId":6},
      {"modelId":57,"modelName":"XT6","brandId":6},
      {"modelId":58,"modelName":"Blazer","brandId":7},
      {"modelId":59,"modelName":"Bolt EV","brandId":7},
      {"modelId":60,"modelName":"Camaro","brandId":7},
      {"modelId":61,"modelName":"Colorado Crew Cab","brandId":7},
      {"modelId":62,"modelName":"Colorado Extended Cab","brandId":7},
      {"modelId":63,"modelName":"Corvette","brandId":7},
      {"modelId":64,"modelName":"Equinox","brandId":7},
      {"modelId":65,"modelName":"Express 2500 Cargo","brandId":7},
      {"modelId":66,"modelName":"Express 3500 Cargo","brandId":7},
      {"modelId":67,"modelName":"Impala","brandId":7},
      {"modelId":68,"modelName":"Malibu","brandId":7},
      {"modelId":69,"modelName":"Silverado 1500 Crew Cab","brandId":7},
      {"modelId":70,"modelName":"Silverado 1500 Double Cab","brandId":7},
      {"modelId":71,"modelName":"Silverado 1500 Regular Cab","brandId":7},
      {"modelId":72,"modelName":"Silverado 2500 HD Crew Cab","brandId":7},
      {"modelId":73,"modelName":"Silverado 2500 HD Double Cab","brandId":7},
      {"modelId":74,"modelName":"Silverado 3500 HD Crew Cab","brandId":7},
      {"modelId":75,"modelName":"Sonic","brandId":7},
      {"modelId":76,"modelName":"Spark","brandId":7},
      {"modelId":77,"modelName":"Suburban","brandId":7},
      {"modelId":78,"modelName":"Tahoe","brandId":7},
      {"modelId":79,"modelName":"Traverse","brandId":7},
      {"modelId":80,"modelName":"Trax","brandId":7},
      {"modelId":81,"modelName":"300","brandId":8},
      {"modelId":82,"modelName":"Pacifica","brandId":8},
      {"modelId":83,"modelName":"Pacifica Hybrid","brandId":8},
      {"modelId":84,"modelName":"Voyager","brandId":8},
      {"modelId":85,"modelName":"Challenger","brandId":9},
      {"modelId":86,"modelName":"Charger","brandId":9},
      {"modelId":87,"modelName":"Durango","brandId":9},
      {"modelId":88,"modelName":"Grand Caravan Passenger","brandId":9},
      {"modelId":89,"modelName":"Journey","brandId":9},
      {"modelId":90,"modelName":"124 Spider","brandId":10},
      {"modelId":91,"modelName":"500L","brandId":10},
      {"modelId":92,"modelName":"500X","brandId":10},
      {"modelId":93,"modelName":"EcoSport","brandId":11},
      {"modelId":94,"modelName":"Edge","brandId":11},
      {"modelId":95,"modelName":"Escape","brandId":11},
      {"modelId":96,"modelName":"Expedition","brandId":11},
      {"modelId":97,"modelName":"Expedition MAX","brandId":11},
      {"modelId":98,"modelName":"Explorer","brandId":11},
      {"modelId":99,"modelName":"F150 Regular Cab","brandId":11},
      {"modelId":100,"modelName":"F150 Super Cab","brandId":11},
      {"modelId":101,"modelName":"F150 SuperCrew Cab","brandId":11},
      {"modelId":102,"modelName":"F250 Super Duty Crew Cab","brandId":11},
      {"modelId":103,"modelName":"F250 Super Duty Regular Cab","brandId":11},
      {"modelId":104,"modelName":"F250 Super Duty Super Cab","brandId":11},
      {"modelId":105,"modelName":"F350 Super Duty Crew Cab","brandId":11},
      {"modelId":106,"modelName":"F350 Super Duty Super Cab","brandId":11},
      {"modelId":107,"modelName":"F450 Super Duty Crew Cab","brandId":11},
      {"modelId":108,"modelName":"Fusion","brandId":11},
      {"modelId":109,"modelName":"Fusion Plug-in Hybrid","brandId":11},
      {"modelId":110,"modelName":"Mustang","brandId":11},
      {"modelId":111,"modelName":"Ranger SuperCab","brandId":11},
      {"modelId":112,"modelName":"Ranger SuperCrew","brandId":11},
      {"modelId":113,"modelName":"Transit 250 Cargo Van","brandId":11},
      {"modelId":114,"modelName":"Transit 350 Passenger Van","brandId":11},
      {"modelId":115,"modelName":"Transit Connect Cargo Van","brandId":11},
      {"modelId":116,"modelName":"Transit Connect Passenger Wagon","brandId":11},
      {"modelId":117,"modelName":"Sprinter 1500 Cargo","brandId":12},
      {"modelId":118,"modelName":"Sprinter 1500 Passenger","brandId":12},
      {"modelId":119,"modelName":"Sprinter 2500 Cargo","brandId":12},
      {"modelId":120,"modelName":"Sprinter 2500 Crew","brandId":12},
      {"modelId":121,"modelName":"Sprinter 2500 Passenger","brandId":12},
      {"modelId":122,"modelName":"Sprinter 3500 Cargo","brandId":12},
      {"modelId":123,"modelName":"Sprinter 3500 Crew","brandId":12},
      {"modelId":124,"modelName":"Sprinter 3500 XD Crew","brandId":12},
      {"modelId":125,"modelName":"Sprinter 3500XD Cargo","brandId":12},
      {"modelId":126,"modelName":"Sprinter 4500 Cargo","brandId":12},
      {"modelId":127,"modelName":"Sprinter 4500 Crew","brandId":12},
      {"modelId":128,"modelName":"G70","brandId":13},
      {"modelId":129,"modelName":"G80","brandId":13},
      {"modelId":130,"modelName":"G90","brandId":13},
      {"modelId":131,"modelName":"Acadia","brandId":14},
      {"modelId":132,"modelName":"Canyon Crew Cab","brandId":14},
      {"modelId":133,"modelName":"Sierra 1500 Crew Cab","brandId":14},
      {"modelId":134,"modelName":"Sierra 1500 Double Cab","brandId":14},
      {"modelId":135,"modelName":"Sierra 1500 Regular Cab","brandId":14},
      {"modelId":136,"modelName":"Sierra 2500 HD Crew Cab","brandId":14},
      {"modelId":137,"modelName":"Sierra 3500 HD Crew Cab","brandId":14},
      {"modelId":138,"modelName":"Terrain","brandId":14},
      {"modelId":139,"modelName":"Yukon","brandId":14},
      {"modelId":140,"modelName":"Yukon XL","brandId":14},
      {"modelId":141,"modelName":"Accord","brandId":15},
      {"modelId":142,"modelName":"Accord Hybrid","brandId":15},
      {"modelId":143,"modelName":"Civic","brandId":15},
      {"modelId":144,"modelName":"Civic Type R","brandId":15},
      {"modelId":145,"modelName":"Clarity Fuel Cell","brandId":15},
      {"modelId":146,"modelName":"Clarity Plug-in Hybrid","brandId":15},
      {"modelId":147,"modelName":"CR-V","brandId":15},
      {"modelId":148,"modelName":"CR-V Hybrid","brandId":15},
      {"modelId":149,"modelName":"Fit","brandId":15},
      {"modelId":150,"modelName":"HR-V","brandId":15},
      {"modelId":151,"modelName":"Insight","brandId":15},
      {"modelId":152,"modelName":"Odyssey","brandId":15},
      {"modelId":153,"modelName":"Passport","brandId":15},
      {"modelId":154,"modelName":"Pilot","brandId":15},
      {"modelId":155,"modelName":"Ridgeline","brandId":15},
      {"modelId":156,"modelName":"Accent","brandId":16},
      {"modelId":157,"modelName":"Elantra","brandId":16},
      {"modelId":158,"modelName":"Elantra GT","brandId":16},
      {"modelId":159,"modelName":"Ioniq Electric","brandId":16},
      {"modelId":160,"modelName":"Ioniq Hybrid","brandId":16},
      {"modelId":161,"modelName":"Ioniq Plug-in Hybrid","brandId":16},
      {"modelId":162,"modelName":"Kona","brandId":16},
      {"modelId":163,"modelName":"Kona Electric","brandId":16},
      {"modelId":164,"modelName":"NEXO","brandId":16},
      {"modelId":165,"modelName":"Palisade","brandId":16},
      {"modelId":166,"modelName":"Santa Fe","brandId":16},
      {"modelId":167,"modelName":"Sonata","brandId":16},
      {"modelId":168,"modelName":"Sonata Hybrid","brandId":16},
      {"modelId":169,"modelName":"Tucson","brandId":16},
      {"modelId":170,"modelName":"Veloster","brandId":16},
      {"modelId":171,"modelName":"Venue","brandId":16},
      {"modelId":172,"modelName":"Q50","brandId":17},
      {"modelId":173,"modelName":"Q60","brandId":17},
      {"modelId":174,"modelName":"QX50","brandId":17},
      {"modelId":175,"modelName":"QX60","brandId":17},
      {"modelId":176,"modelName":"QX80","brandId":17},
      {"modelId":177,"modelName":"E-PACE","brandId":18},
      {"modelId":178,"modelName":"F-PACE","brandId":18},
      {"modelId":179,"modelName":"F-TYPE","brandId":18},
      {"modelId":180,"modelName":"I-PACE","brandId":18},
      {"modelId":181,"modelName":"XE","brandId":18},
      {"modelId":182,"modelName":"XF","brandId":18},
      {"modelId":183,"modelName":"Cherokee","brandId":19},
      {"modelId":184,"modelName":"Compass","brandId":19},
      {"modelId":185,"modelName":"Gladiator","brandId":19},
      {"modelId":186,"modelName":"Grand Cherokee","brandId":19},
      {"modelId":187,"modelName":"Renegade","brandId":19},
      {"modelId":188,"modelName":"Wrangler","brandId":19},
      {"modelId":189,"modelName":"Wrangler Unlimited","brandId":19},
      {"modelId":190,"modelName":"Cadenza","brandId":20},
      {"modelId":191,"modelName":"Forte","brandId":20},
      {"modelId":192,"modelName":"K900","brandId":20},
      {"modelId":193,"modelName":"Niro","brandId":20},
      {"modelId":194,"modelName":"Niro EV","brandId":20},
      {"modelId":195,"modelName":"Niro Plug-in Hybrid","brandId":20},
      {"modelId":196,"modelName":"Optima","brandId":20},
      {"modelId":197,"modelName":"Optima Hybrid","brandId":20},
      {"modelId":198,"modelName":"Optima Plug-in Hybrid","brandId":20},
      {"modelId":199,"modelName":"Rio","brandId":20},
      {"modelId":200,"modelName":"Sedona","brandId":20},
      {"modelId":201,"modelName":"Sorento","brandId":20},
      {"modelId":202,"modelName":"Soul","brandId":20},
      {"modelId":203,"modelName":"Sportage","brandId":20},
      {"modelId":204,"modelName":"Stinger","brandId":20},
      {"modelId":205,"modelName":"Telluride","brandId":20},
      {"modelId":206,"modelName":"Defender 110","brandId":21},
      {"modelId":207,"modelName":"Defender 90","brandId":21},
      {"modelId":208,"modelName":"Discovery","brandId":21},
      {"modelId":209,"modelName":"Discovery Sport","brandId":21},
      {"modelId":210,"modelName":"Range Rover","brandId":21},
      {"modelId":211,"modelName":"Range Rover Evoque","brandId":21},
      {"modelId":212,"modelName":"Range Rover Sport","brandId":21},
      {"modelId":213,"modelName":"Range Rover Velar","brandId":21},
      {"modelId":214,"modelName":"ES","brandId":22},
      {"modelId":215,"modelName":"GS","brandId":22},
      {"modelId":216,"modelName":"GX","brandId":22},
      {"modelId":217,"modelName":"IS","brandId":22},
      {"modelId":218,"modelName":"LC","brandId":22},
      {"modelId":219,"modelName":"LS","brandId":22},
      {"modelId":220,"modelName":"LX","brandId":22},
      {"modelId":221,"modelName":"NX","brandId":22},
      {"modelId":222,"modelName":"RC","brandId":22},
      {"modelId":223,"modelName":"RX","brandId":22},
      {"modelId":224,"modelName":"UX","brandId":22},
      {"modelId":225,"modelName":"Aviator","brandId":23},
      {"modelId":226,"modelName":"Continental","brandId":23},
      {"modelId":227,"modelName":"Corsair","brandId":23},
      {"modelId":228,"modelName":"MKZ","brandId":23},
      {"modelId":229,"modelName":"Nautilus","brandId":23},
      {"modelId":230,"modelName":"Navigator","brandId":23},
      {"modelId":231,"modelName":"Navigator L","brandId":23},
      {"modelId":232,"modelName":"CX-3","brandId":24},
      {"modelId":233,"modelName":"CX-30","brandId":24},
      {"modelId":234,"modelName":"CX-5","brandId":24},
      {"modelId":235,"modelName":"CX-9","brandId":24},
      {"modelId":236,"modelName":"MAZDA3","brandId":24},
      {"modelId":237,"modelName":"MAZDA6","brandId":24},
      {"modelId":238,"modelName":"MX-5 Miata","brandId":24},
      {"modelId":239,"modelName":"MX-5 Miata RF","brandId":24},
      {"modelId":240,"modelName":"A-Class","brandId":25},
      {"modelId":241,"modelName":"C-Class","brandId":25},
      {"modelId":242,"modelName":"CLA","brandId":25},
      {"modelId":243,"modelName":"CLS","brandId":25},
      {"modelId":244,"modelName":"E-Class","brandId":25},
      {"modelId":245,"modelName":"G-Class","brandId":25},
      {"modelId":246,"modelName":"GLA","brandId":25},
      {"modelId":247,"modelName":"GLB","brandId":25},
      {"modelId":248,"modelName":"GLC","brandId":25},
      {"modelId":249,"modelName":"GLE","brandId":25},
      {"modelId":250,"modelName":"GLS","brandId":25},
      {"modelId":251,"modelName":"Mercedes-AMG A-Class","brandId":25},
      {"modelId":252,"modelName":"Mercedes-AMG C-Class","brandId":25},
      {"modelId":253,"modelName":"Mercedes-AMG CLS","brandId":25},
      {"modelId":254,"modelName":"Mercedes-AMG GLC","brandId":25},
      {"modelId":255,"modelName":"Mercedes-AMG GLC Coupe","brandId":25},
      {"modelId":256,"modelName":"Metris WORKER Cargo","brandId":25},
      {"modelId":257,"modelName":"Metris WORKER Passenger","brandId":25},
      {"modelId":258,"modelName":"S-Class","brandId":25},
      {"modelId":259,"modelName":"SLC","brandId":25},
      {"modelId":260,"modelName":"Sprinter 1500 Cargo","brandId":25},
      {"modelId":261,"modelName":"Sprinter 1500 Passenger","brandId":25},
      {"modelId":262,"modelName":"Sprinter 2500 Cargo","brandId":25},
      {"modelId":263,"modelName":"Sprinter 2500 Crew","brandId":25},
      {"modelId":264,"modelName":"Sprinter 2500 Passenger","brandId":25},
      {"modelId":265,"modelName":"Sprinter 3500 Cargo","brandId":25},
      {"modelId":266,"modelName":"Sprinter 3500 Crew","brandId":25},
      {"modelId":267,"modelName":"Sprinter 3500 XD Cargo","brandId":25},
      {"modelId":268,"modelName":"Sprinter 3500 XD Crew","brandId":25},
      {"modelId":269,"modelName":"Sprinter 4500 Cargo","brandId":25},
      {"modelId":270,"modelName":"Sprinter 4500 Crew","brandId":25},
      {"modelId":271,"modelName":"Clubman","brandId":26},
      {"modelId":272,"modelName":"Countryman","brandId":26},
      {"modelId":273,"modelName":"Hardtop 2 Door","brandId":26},
      {"modelId":274,"modelName":"Hardtop 4 Door","brandId":26},
      {"modelId":275,"modelName":"Eclipse Cross","brandId":27},
      {"modelId":276,"modelName":"Mirage","brandId":27},
      {"modelId":277,"modelName":"Mirage G4","brandId":27},
      {"modelId":278,"modelName":"Outlander","brandId":27},
      {"modelId":279,"modelName":"Outlander PHEV","brandId":27},
      {"modelId":280,"modelName":"Outlander Sport","brandId":27},
      {"modelId":281,"modelName":"370Z","brandId":28},
      {"modelId":282,"modelName":"Altima","brandId":28},
      {"modelId":283,"modelName":"Armada","brandId":28},
      {"modelId":284,"modelName":"Frontier Crew Cab","brandId":28},
      {"modelId":285,"modelName":"Frontier King Cab","brandId":28},
      {"modelId":286,"modelName":"GT-R","brandId":28},
      {"modelId":287,"modelName":"Kicks","brandId":28},
      {"modelId":288,"modelName":"LEAF","brandId":28},
      {"modelId":289,"modelName":"Maxima","brandId":28},
      {"modelId":290,"modelName":"Murano","brandId":28},
      {"modelId":291,"modelName":"NV1500 Cargo","brandId":28},
      {"modelId":292,"modelName":"NV200","brandId":28},
      {"modelId":293,"modelName":"NV2500 HD Cargo","brandId":28},
      {"modelId":294,"modelName":"NV3500 HD Cargo","brandId":28},
      {"modelId":295,"modelName":"NV3500 HD Passenger","brandId":28},
      {"modelId":296,"modelName":"Pathfinder","brandId":28},
      {"modelId":297,"modelName":"Rogue","brandId":28},
      {"modelId":298,"modelName":"Rogue Sport","brandId":28},
      {"modelId":299,"modelName":"Sentra","brandId":28},
      {"modelId":300,"modelName":"Titan Crew Cab","brandId":28},
      {"modelId":301,"modelName":"Titan King Cab","brandId":28},
      {"modelId":302,"modelName":"TITAN XD Crew Cab","brandId":28},
      {"modelId":303,"modelName":"Versa","brandId":28},
      {"modelId":304,"modelName":"718 Boxster","brandId":29},
      {"modelId":305,"modelName":"718 Cayman","brandId":29},
      {"modelId":306,"modelName":"718 Spyder","brandId":29},
      {"modelId":307,"modelName":"911","brandId":29},
      {"modelId":308,"modelName":"Cayenne","brandId":29},
      {"modelId":309,"modelName":"Cayenne Coupe","brandId":29},
      {"modelId":310,"modelName":"Macan","brandId":29},
      {"modelId":311,"modelName":"Panamera","brandId":29},
      {"modelId":312,"modelName":"Taycan","brandId":29},
      {"modelId":313,"modelName":"1500 Classic Crew Cab","brandId":30},
      {"modelId":314,"modelName":"1500 Classic Quad Cab","brandId":30},
      {"modelId":315,"modelName":"1500 Crew Cab","brandId":30},
      {"modelId":316,"modelName":"1500 Quad Cab","brandId":30},
      {"modelId":317,"modelName":"2500 Crew Cab","brandId":30},
      {"modelId":318,"modelName":"3500 Crew Cab","brandId":30},
      {"modelId":319,"modelName":"ProMaster Cargo Van","brandId":30},
      {"modelId":320,"modelName":"ProMaster City","brandId":30},
      {"modelId":321,"modelName":"Ascent","brandId":31},
      {"modelId":322,"modelName":"BRZ","brandId":31},
      {"modelId":323,"modelName":"Crosstrek","brandId":31},
      {"modelId":324,"modelName":"Forester","brandId":31},
      {"modelId":325,"modelName":"Impreza","brandId":31},
      {"modelId":326,"modelName":"Legacy","brandId":31},
      {"modelId":327,"modelName":"Outback","brandId":31},
      {"modelId":328,"modelName":"WRX","brandId":31},
      {"modelId":329,"modelName":"Model 3","brandId":32},
      {"modelId":330,"modelName":"Model S","brandId":32},
      {"modelId":331,"modelName":"Model X","brandId":32},
      {"modelId":332,"modelName":"Model Y","brandId":32},
      {"modelId":333,"modelName":"4Runner","brandId":33},
      {"modelId":334,"modelName":"86","brandId":33},
      {"modelId":335,"modelName":"Avalon","brandId":33},
      {"modelId":336,"modelName":"Avalon Hybrid","brandId":33},
      {"modelId":337,"modelName":"Camry","brandId":33},
      {"modelId":338,"modelName":"Camry Hybrid","brandId":33},
      {"modelId":339,"modelName":"C-HR","brandId":33},
      {"modelId":340,"modelName":"Corolla","brandId":33},
      {"modelId":341,"modelName":"Corolla Hatchback","brandId":33},
      {"modelId":342,"modelName":"Corolla Hybrid","brandId":33},
      {"modelId":343,"modelName":"GR Supra","brandId":33},
      {"modelId":344,"modelName":"Highlander","brandId":33},
      {"modelId":345,"modelName":"Highlander Hybrid","brandId":33},
      {"modelId":346,"modelName":"Land Cruiser","brandId":33},
      {"modelId":347,"modelName":"Mirai","brandId":33},
      {"modelId":348,"modelName":"Prius","brandId":33},
      {"modelId":349,"modelName":"Prius Prime","brandId":33},
      {"modelId":350,"modelName":"RAV4","brandId":33},
      {"modelId":351,"modelName":"RAV4 Hybrid","brandId":33},
      {"modelId":352,"modelName":"Sequoia","brandId":33},
      {"modelId":353,"modelName":"Sienna","brandId":33},
      {"modelId":354,"modelName":"Tacoma Access Cab","brandId":33},
      {"modelId":355,"modelName":"Tacoma Double Cab","brandId":33},
      {"modelId":356,"modelName":"Tundra CrewMax","brandId":33},
      {"modelId":357,"modelName":"Tundra Double Cab","brandId":33},
      {"modelId":358,"modelName":"Yaris","brandId":33},
      {"modelId":359,"modelName":"Yaris Hatchback","brandId":33},
      {"modelId":360,"modelName":"Arteon","brandId":34},
      {"modelId":361,"modelName":"Atlas","brandId":34},
      {"modelId":362,"modelName":"Atlas Cross Sport","brandId":34},
      {"modelId":363,"modelName":"Golf","brandId":34},
      {"modelId":364,"modelName":"Golf GTI","brandId":34},
      {"modelId":365,"modelName":"Jetta","brandId":34},
      {"modelId":366,"modelName":"Jetta GLI","brandId":34},
      {"modelId":367,"modelName":"Passat","brandId":34},
      {"modelId":368,"modelName":"Tiguan","brandId":34},
      {"modelId":369,"modelName":"S60","brandId":35},
      {"modelId":370,"modelName":"S90","brandId":35},
      {"modelId":371,"modelName":"V60","brandId":35},
      {"modelId":372,"modelName":"V90","brandId":35},
      {"modelId":373,"modelName":"XC40","brandId":35},
      {"modelId":374,"modelName":"XC60","brandId":35},
      {"modelId":375,"modelName":"XC90","brandId":35}
    ];
    this.brandList = [
      {"brandId":1,"brandName":"Acura"},
      {"brandId":2,"brandName":"Alfa Romeo"},
      {"brandId":3,"brandName":"Audi"},
      {"brandId":4,"brandName":"BMW"},
      {"brandId":5,"brandName":"Buick"},
      {"brandId":6,"brandName":"Cadillac"},
      {"brandId":7,"brandName":"Chevrolet"},
      {"brandId":8,"brandName":"Chrysler"},
      {"brandId":9,"brandName":"Dodge"},
      {"brandId":10,"brandName":"FIAT"},
      {"brandId":11,"brandName":"Ford"},
      {"brandId":12,"brandName":"Freightliner"},
      {"brandId":13,"brandName":"Genesis"},
      {"brandId":14,"brandName":"GMC"},
      {"brandId":15,"brandName":"Honda"},
      {"brandId":16,"brandName":"Hyundai"},
      {"brandId":17,"brandName":"INFINITI"},
      {"brandId":18,"brandName":"Jaguar"},
      {"brandId":19,"brandName":"Jeep"},
      {"brandId":20,"brandName":"Kia"},
      {"brandId":21,"brandName":"Land Rover"},
      {"brandId":22,"brandName":"Lexus"},
      {"brandId":23,"brandName":"Lincoln"},
      {"brandId":24,"brandName":"MAZDA"},
      {"brandId":25,"brandName":"Mercedes-Benz"},
      {"brandId":26,"brandName":"MINI"},
      {"brandId":27,"brandName":"Mitsubishi"},
      {"brandId":28,"brandName":"Nissan"},
      {"brandId":29,"brandName":"Porsche"},
      {"brandId":30,"brandName":"Ram"},
      {"brandId":31,"brandName":"Subaru"},
      {"brandId":32,"brandName":"Tesla"},
      {"brandId":33,"brandName":"Toyota"},
      {"brandId":34,"brandName":"Volkswagen"},
      {"brandId":35,"brandName":"Volvo"}
    ];
  }
}
